### ISSUE TITLE
new react version support

### ISSUE THREAD

**Issue by AsasinCree** [v0ltoz/react-datetimepicker#24]
Here's an example both react and react-dom version is "16.8.1" and error appeared like this
![image](https://user-images.githubusercontent.com/18276301/57270070-70ca9d00-70bc-11e9-994d-050fc5bf2cb1.png)
https://codesandbox.io/embed/q718414r14

**Comment by v0ltoz** [comment]
Thanks for the comment.

I have now released a new version which supports both React 15 and React 16. This will now work in your demo alongside the FormControl fix.

The example is best used with bootstrap

React 15 Demo 
https://codesandbox.io/s/zxoo178m03?fontsize=14&module=%2Fsrc%2FApp.js 

React 16 Demo 
https://codesandbox.io/s/v6z8l7nr8y?fontsize=14&module=%2Fsrc%2FApp.js

**Comment by AsasinCree** [comment]
What if react version update in the feature, this issue will appear again?

**Comment by v0ltoz** [comment]
The implemented change means the picker itself doesn't depend on any version of React whereas before it was dependent on React 15 as I had it as a dependency. This was a mistake which is fixed. 

If React updated and introduced new depreciated lifecycle methods in the next version then these will need to be fixed. But other than that this component will still work and will be unaffected by React updates
