### ISSUE TITLE
Console shows warning on deprecated componentWillMount usage

### ISSUE THREAD

**Issue by LakshmiVeejai** [v0ltoz/react-datetimepicker#44]
Will React 16, componentWillMount is deprecated and console is filled with below warning

_Warning: componentWillMount has been renamed, and is not recommended for us
Please update the following components: DateTimeRangeContainer_

**Comment by LakshmiVeejai** [comment]
Can I go ahead and patch and raise PR @v0ltoz

**Comment by v0ltoz** [comment]
A PR with a fix would be appreciated, thanks

**Comment by LakshmiVeejai** [comment]
@v0ltoz here you go #48

**Comment by v0ltoz** [comment]
Thanks 🥇 
Published to NPM now
