### ISSUE TITLE
Please add License file to the repo

### ISSUE THREAD

**Issue by kashifshamaz21** [v0ltoz/react-datetimepicker#51]
@v0ltoz Filing this ticket to place a request for including a license file to the repo, if that is fine with you and other contributors of this library. Thanks.

**Comment by ankitsharan15** [comment]
Yes, Please add a licence in the repository.

**Comment by thelethalhawk** [comment]
+1

**Comment by v0ltoz** [comment]
License added

**Comment by kashifshamaz21** [comment]
Hi @v0ltoz 
Thanks for the speedy resolution, appreciate it. Just a quick note, I guess the `package.json` also needs to be updated to reflect the license type. It currently reads `"license": "GNU"`. 

Also, I would be happy to help out with any bug-fixes to the repository, pls feel free to let me know if there any specific ones that you would like to be picked up first.
